apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: django-app
  labels:
   app: django-app

spec: 
 replicas: 2
 selector:
   matchLabels:
     app: django-app
 template: 
  metadata: 
    namespace: django-app
    labels: 
     app: django-app
  spec: 
   containers: 
     - name: django-app
       image: trainwithshubham/django-todo:latest
       ports:
         - containerPort: 8000
    

    



