apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django-app

spec:
  selector:
   app: django-app
  type: NodePort
  ports: 
   - protocol: TCP
     port: 80
     targetPort: 8000
     nodePort: 30009

